import {chromium} from 'playwright'
import {build} from 'esbuild'
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs'
import assert from 'node:assert/strict'
import {FROZEN,seed,settleAny,settle,go} from '../tools/visual.mjs'
const out='reviews/evidence/glucose-memo';mkdirSync(out,{recursive:true})
const source=`import React from 'react';import {createRoot} from 'react-dom/client';import App from './src/App';import {Memo} from './src/ui/Memo';import {dosing} from './src/logic/regimen';import {installPlatform} from './src/platform/ports';import {webPlatform} from './src/platform/web';window.queue=[];window.shared=null;window.saved=null;window.action=null;installPlatform({...webPlatform,files:{...webPlatform.files,shareText:async(text,title)=>{window.shared={text,title};return true},save:async(name,text,mime)=>{window.saved={name,text,mime};return true}},reminders:{...webPlatform.reminders,isSupported:()=>true,onAction:fn=>{window.action=fn;return()=>{}},permission:async()=>'granted',requestPermission:async()=>'granted',exactTiming:async()=>true,health:async()=>({scheduled:10,until:Date.now()+86400000}),isQuietModeOn:async()=>false,isBatteryRestricted:async()=>false,schedule:async(items,sound)=>{window.queue=items;window.sound=sound},cancelAll:async()=>{window.queue=[]}}});const root=createRoot(document.getElementById('root'));root.render(<App/>);window.memo=()=>{const now=new Date().setHours(0,0,0,0);const meds=[['До','before',20],['Любое',undefined,undefined],['Во время','during',undefined],['После','after',30]].map(([name,meal,mealMinutes],i)=>dosing({id:'b'+i,name,dose:'5 мг',form:'Таблетки',left:30,stockUnit:'piece',doseUnit:'piece'},{id:'r'+i,medicineId:'b'+i,person:'p1',times:['08:00'],perTime:1,since:now,meal,mealMinutes,endsAt:i===0?now+86400000:undefined}));root.render(<div className="app"><Memo medicines={meds} slots={[{id:'a',title:'Утром',time:'08:00'}]} person='Я' onBack={()=>{}}/></div>)};`
const bundle=(await build({stdin:{contents:source,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'iife',jsx:'automatic',loader:{'.md':'text'}})).outputFiles[0].text
const html=`<html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${readFileSync('src/app.css','utf8')}</style><div id="root"></div><script>${bundle.replaceAll('</script','<\\/script')}</script></html>`
const browser=await chromium.launch();const errors=[],checks=[]
try{for(const text of ['normal','xlarge']){
 const context=await browser.newContext({viewport:{width:360,height:900},hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.route('https://glucose.test/**',r=>r.fulfill({contentType:'text/html',body:html}));await page.clock.install({time:new Date(FROZEN)});await page.goto('https://glucose.test');await settleAny(page);await seed(page,FROZEN);
 await page.evaluate(async text=>{const db=await new Promise(r=>{const q=indexedDB.open('omron-bp');q.onsuccess=()=>r(q.result)});const settings=await new Promise(r=>{const q=db.transaction('meta').objectStore('meta').get('settings');q.onsuccess=()=>r(q.result)});await new Promise(r=>{const tx=db.transaction(['meta','readings'],'readwrite');tx.objectStore('readings').clear();[4,6,8,10,12].forEach((mmol,i)=>tx.objectStore('readings').put({id:'g'+i,kind:'glucose',ts:Date.now()-i*60000,mmol,context:i<2?'fasting':'after-meal',user:1,source:'manual'}));tx.objectStore('readings').put({id:'other',kind:'glucose',ts:Date.now(),mmol:30,context:'fasting',user:2,source:'manual'});tx.objectStore('meta').put({...settings,textScale:text,trackGlucose:true,remindersOn:false,measureRemindOn:false,glucoseTimers:[],reminderSound:'silent',notificationHistory:[]},'settings');tx.oncomplete=r});db.close()},text);
 await page.reload();await settle(page);await go(page,{tab:'Сахар'});
 const avg=page.locator('.card').filter({has:page.getByText('Общая средняя сахара',{exact:true})});assert.match(await avg.textContent(),/8,0/);const strip=page.locator('.stats-strip');assert.match(await strip.textContent(),/Средняя натощак5,0/);assert.match(await strip.textContent(),/Средняя через 2 часа после еды10,0/);
 await page.getByText('Подробные показатели сахара',{exact:true}).click();assert.match(await page.locator('details[open]').textContent(),/Медиана: 8,0/);
 await page.getByRole('button',{name:'Напомнить померить сахар через 2 часа',exact:true}).click();await page.waitForFunction(()=>window.queue.some(r=>r.kind==='glucose'));let timer=await page.evaluate(()=>window.queue.find(r=>r.kind==='glucose'));const started=await page.evaluate(async()=>{const db=await new Promise(r=>{const q=indexedDB.open('omron-bp');q.onsuccess=()=>r(q.result)});const st=await new Promise(r=>{const q=db.transaction('meta').objectStore('meta').get('settings');q.onsuccess=()=>r(q.result)});db.close();return st.glucoseTimers.find(t=>!t.cancelledAt).startedAt});assert.equal(timer.at-started,7200000);assert.equal(timer.person,'p1');assert.equal(await page.evaluate(()=>window.sound),'silent');assert(await page.getByRole('button',{name:'Напомнить померить сахар через 2 часа',exact:true}).isDisabled());
 await page.screenshot({path:`${out}/${text}-sugar.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.reload();await settle(page);await go(page,{tab:'Сахар'});assert(await page.getByRole('button',{name:'Отменить напоминание',exact:true}).isVisible());await page.getByRole('button',{name:'Отменить напоминание',exact:true}).click();await page.waitForFunction(()=>!window.queue.some(r=>r.kind==='glucose'));
 await page.getByRole('button',{name:'Напомнить померить сахар через 2 часа',exact:true}).click();await page.waitForFunction(()=>window.queue.some(r=>r.kind==='glucose'));await page.clock.fastForward(7200000);await page.getByText('Прошло 2 часа — пора измерить сахар и записать результат.',{exact:true}).waitFor();
 await page.evaluate(()=>window.action({kind:'open',about:'glucose',person:'p1',day:Date.now()}));await page.getByRole('group',{name:'Момент замера — от него зависит норма'}).getByRole('button',{name:'2 ч после еды',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'2 ч после еды',exact:true}).getAttribute('aria-pressed'),'true');
 await page.evaluate(()=>window.memo());await page.getByRole('button',{name:'Поделиться памяткой',exact:true}).click();await page.waitForFunction(()=>window.shared);const shared=await page.evaluate(()=>window.shared.text);for(const phrase of ['Приём лекарств — Я','За 20 мин до еды','Независимо от еды','Во время еды','Через 30 мин после еды'])assert(shared.includes(phrase));const before=shared.split('• До')[1].split('• Любое')[0];assert(!before.includes('ежедневно'),'Short course must have explicit dates');assert.equal((before.match(/2026/g)||[]).length,2,'Only its two actual intake dates');
 await page.getByRole('button',{name:'Сохранить текст памятки',exact:true}).click();await page.waitForFunction(()=>window.saved);assert.equal(await page.evaluate(()=>window.saved.text),shared);const rows=page.locator('.memo__table').first().locator('tbody tr');assert.equal(await rows.count(),4);assert.equal(await rows.first().locator('.memo__box--off').count(),5);await page.screenshot({path:`${out}/${text}-memo.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.emulateMedia({media:'print'});assert.equal(await page.getByRole('button',{name:'Поделиться памяткой',exact:true}).isVisible(),false);await page.screenshot({path:`${out}/${text}-memo-print.png`,fullPage:true});await page.pdf({path:`${out}/${text}-memo.pdf`,format:'A4',printBackground:false});checks.push({text,averages:true,personIsolation:true,twoHours:true,persisted:true,cancel:true,silent:true,notificationRoute:true,share:true,save:true,shortCourse:true,print:true});await context.close()
}assert.deepEqual(errors,[]);writeFileSync(`${out}/checks.json`,JSON.stringify({checks,errors},null,2));console.log('Glucose/memo actual UI: normal and xlarge touch passed')
}finally{await browser.close()}
